"""grant permissions

Revision ID: 05a76e0681aa
Revises: 
Create Date: 2024-07-29 00:19:04.216866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a76e0681aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nrega_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('nrega_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nrega_id')
    )
    op.create_table('nrega_work_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('nrega_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nrega_id')
    )
    op.create_table('nrega_districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('nrega_id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['nrega_states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nrega_id')
    )
    op.create_table('nrega_work_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('nrega_id', sa.Integer(), nullable=False),
    sa.Column('work_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_category_id'], ['nrega_work_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nrega_id')
    )
    op.create_table('nrega_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('nrega_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['nrega_districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nrega_panchayats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('nrega_id', sa.BigInteger(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['nrega_blocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nrega_id')
    )
    op.create_table('nrega_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('asset_id', sa.String(length=40), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('work_name', sa.String(length=80), nullable=True),
    sa.Column('work_code', sa.String(length=80), nullable=True),
    sa.Column('work_type_id', sa.Integer(), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['panchayat_id'], ['nrega_panchayats.id'], ),
    sa.ForeignKeyConstraint(['work_type_id'], ['nrega_work_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nrega_assets')
    op.drop_table('nrega_panchayats')
    op.drop_table('nrega_blocks')
    op.drop_table('nrega_work_types')
    op.drop_table('nrega_districts')
    op.drop_table('nrega_work_categories')
    op.drop_table('nrega_states')
    # ### end Alembic commands ###
