"""add inputs tables

Revision ID: 37e4e798c919
Revises: 610251d1f581
Create Date: 2024-08-02 16:55:32.007934

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '37e4e798c919'
down_revision = '610251d1f581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Your autogenerated commands here
    # Modify the nrega_assets table
    op.add_column('nrega_assets', sa.Column('work_name', sa.String(length=500), nullable=True))

    # Create input_parameters_master table
    op.create_table('input_parameters_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Create input_proposed_status table
    op.create_table('input_proposed_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('proposed_status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['input_id'], ['input_parameters_master.id'], ),
    sa.ForeignKeyConstraint(['proposed_status_id'], ['proposed_status_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Grant permissions
    op.execute("GRANT ALL PRIVILEGES ON SCHEMA public TO zeidwhrc;")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Your autogenerated commands here
    # Drop input_proposed_status table
    op.drop_table('input_proposed_status')

    # Drop input_parameters_master table
    op.drop_table('input_parameters_master')

    # Remove the work_name column from nrega_assets table
    op.drop_column('nrega_assets', 'work_name')
    # ### end Alembic commands ###

    # Revoke permissions if necessary
    op.execute("REVOKE ALL PRIVILEGES ON SCHEMA public FROM zeidwhrc;")
