"""add assets table

Revision ID: 469028ab3f15
Revises: 37e4e798c919
Create Date: 2024-08-04 18:17:24.238452

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '469028ab3f15'
down_revision = '37e4e798c919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Your autogenerated commands here
    op.create_table('assets_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('input_value', sa.String(length=100), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('proposed_status_id', sa.Integer(), nullable=False),
    sa.Column('input_id', sa.Integer(), nullable=False),
    sa.Column('panchayat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['nrega_assets.id'], ),
    sa.ForeignKeyConstraint(['input_id'], ['input_parameters_master.id'], ),
    sa.ForeignKeyConstraint(['proposed_status_id'], ['proposed_status_master.id'], ),
    sa.ForeignKeyConstraint(['panchayat_id'], ['nrega_panchayats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Grant permissions
    op.execute("GRANT ALL PRIVILEGES ON SCHEMA public TO zeidwhrc;")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Your autogenerated commands here
    op.drop_table('assets_data')
    # ### end Alembic commands ###

    # Revoke permissions if necessary
    op.execute("REVOKE ALL PRIVILEGES ON SCHEMA public FROM zeidwhrc;")
