"""cost allow_null

Revision ID: 8a39051a79a2
Revises: 05a76e0681aa
Create Date: 2024-07-29 00:25:49.740965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a39051a79a2'
down_revision = '05a76e0681aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Your autogenerated commands here
    # ### end Alembic commands ###

    # Grant permissions
    op.execute("GRANT ALL PRIVILEGES ON SCHEMA public TO zeidwhrc;")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Your autogenerated commands here
    # ### end Alembic commands ###

    # Revoke permissions if necessary
    op.execute("REVOKE ALL PRIVILEGES ON SCHEMA public FROM zeidwhrc;")
